name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Setup npm
        run: npm install -g npm@7
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Setup npm
        run: npm install -g npm@7
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run build
        run: npm run build
        env:
          NODE_ENV: production
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Setup npm
        run: npm install -g npm@7
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run lint
        run: npm run lint -- --no-fix
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Setup npm
        run: npm install -g npm@7
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run type-check
        run: npm run type-check
